[application]

[web.app]

# HTML title tag content
title = "nex_cafe_server"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "com.nexcafe.server"
publisher = "John Kenneth Racelis"
icon = ["icons/icon.ico"]

[web.watcher]
# when watcher trigger, regenerate the `index.html`
reload_html = true
# which files or dirs will be watcher monitoring
watch_path = ["src"]